### ISSUE TITLE
Compile?

### ISSUE THREAD

**Issue by nicoco007** [Pupix/lol-inibin-parser#1]
Is there any way to compile the read files?

**Comment by Pupix** [comment]
Not currently. From looking around the files I noticed that Riot compresses the values randomly, sometimes the numbers/booleans are presented as strings in the final .inibin. I am not exactly sure how to go about compiling back an inibin file.

**Comment by nicoco007** [comment]
Oh, okay. That's a shame. Thanks!

**Comment by nicoco007** [comment]
I had an idea, but I haven't been very successful in getting it to work. Do you think it would be possible to edit the values of an inibin file using something like a hex/binary editor? If so, how would you find out which values are what?

**Comment by Pupix** [comment]
Using a hex editor (010 editor) you can create a template following the code [here](https://github.com/Pupix/lol-inibin-parser/blob/master/lib/parse.js#L39). At the end you will have a list of keys and values, most of which have been mapped [here](https://github.com/Pupix/lol-hash-table/blob/master/lib/index.js). You will either have to check manually or create a finder, something like [this](https://github.com/Pupix/lol-inibin-parser/blob/master/lib/util/matchHash.js), to understand a key's meaning.

**Comment by nicoco007** [comment]
Thanks! That worked perfectly!
