### ISSUE TITLE
.bin files

### ISSUE THREAD

**Issue by nicoco007** [Pupix/lol-inibin-parser#2]
Sorry to bother you again, but do you know if it is possible to parse .bin files? I found out that some information is missing from inibin files (mostly MeshSkin stuff) for certain champions (e.g. Nautilus and Zac), and instead have a .bin file. These files seem to contain similar information to the inibin files, but not under the same format. Any ideas?

**Comment by Pupix** [comment]
Yes, I have tried in the past to parse it but got sidetracked by other things. However the .bin files I was trying to read were the UI ones, don't know if the structure is the same for all of them.

edit: Read below.

**Comment by Pupix** [comment]
This is a more complete version of the template : https://gist.github.com/Pupix/0b6aadaacabe3078d17c

Also put a js version up [on github](https://github.com/Pupix/lol-bin-parser) and as an [npm module](https://www.npmjs.com/package/lol-bin-parser)

**Comment by nicoco007** [comment]
Great, thank you very much!
