### ISSUE TITLE
XP.mapOne errors & unknown data

### ISSUE THREAD

**Issue by nicoco007** [Pupix/lol-inibin-parser#3]
I'm sometimes getting "XP.mapOne is not a function" errors on certain champions' (e.g. Nautilus & Zac) inibin files when using InibinParser.read(), and the ones that trigger the error often have keys that are not in your lol-hash-table project and are missing keys from some categories (e.g. MeshSkin). Any idea why?

**Comment by Pupix** [comment]
Sorry about that. The dependencies are out of sync. mapOne has been removed from `expandjs 0.10.0` and the dependency was set to the latest version instead of the one that the parser actually relies on.

Just update the module via NPM and you are good to go.

Cheers.

OT: May I ask what you are building with all these parsers?

**Comment by nicoco007** [comment]
Thanks! I'm actually mostly screwing around and doing dumb stuff like this:
![dumb stuff](https://cloud.githubusercontent.com/assets/1349975/13061491/318bbd0a-d406-11e5-80bf-15c3fb9b277f.png)

Another question: Do you happen to know why keys under `MeshSkin` don't exist in some characters' inibin files? Here's an example: https://dl.dropboxusercontent.com/u/49088008/read.json

**Comment by Pupix** [comment]
Glad you are having fun.

Sometimes a champion's .inibin file has missing MeshSkin data because Riot split said data in different files which can be found in the `skins` folder of each champion.

**Comment by nicoco007** [comment]
Some champions seem to not have those either:
![files extractor](https://cloud.githubusercontent.com/assets/1349975/13165650/514666b6-d68d-11e5-81ed-88d527586810.png)

**Comment by nicoco007** [comment]
Okay, I just found out that Riot started moving everything to .bin files and completely getting rid of .inibin files (I guess it makes it more uniform or something). The previously named "MeshSkin" category is now in the .bin file, under keys where "755834653": "Flesh" is present and "762889000" has the skin name/number as the value.
